### PR TITLE
Map solr 'facets' field to json_facets

### LINKED ISSUE #213: Add support for json.facets
The json.facet parameter allows for powerful aggregate queries on facets:

http://yonik.com/solr-count-distinct/

The solr response is populated with a new object called 'facets', e.g.

However, pysolr provides no way of accessing this object. In the pysolr object, the field 'facets' is used for what solr called 'facet_counts':

https://github.com/django-haystack/pysolr/blob/master/pysolr.py#L273

I suggest that this part of the solr response gets mapped to a field 'json_facets'

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #213

### CODE REVIEW

**Comment by cmungall** [comment]
It's not clear to me why some of the build configurations fail.

https://travis-ci.org/django-haystack/pysolr/jobs/188412518#L309-L374

```
118.84s$ python run-tests.py
Installed SIGUSR1 handler to print stack traces: pkill -USR1 -f run-tests
Removing stale working files
Preparing SOLR_HOME for tests at /home/travis/build/django-haystack/pysolr/solr
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 1147, in getresponse
    response.begin()
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 358, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 320, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.3.5/lib/python3.3/socket.py", line 297, in readinto
    return self._sock.recv_into(b)
ConnectionResetError
```

**Comment by acdha** [comment]
I just restarted those build tasks – it might have just been congestion on the build workers.

**Comment by cmungall** [comment]
Better this time, all pass except one, which gives:

```
$ python run-tests.py
Installed SIGUSR1 handler to print stack traces: pkill -USR1 -f run-tests
Removing stale working files
Preparing SOLR_HOME for tests at /home/travis/build/django-haystack/pysolr/solr
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by acdha** [comment]
One more retry fixed that one.

**Comment by acdha** [comment]
Is there any other post-processing which makes sense to do here? I was thinking that we should update the documentation to clarify the difference between `.facets` and `.json_facets` but also wanted to make it clear why this isn't just `.raw_response['json_facets']`.

**Comment by cmungall** [comment]
On reflection, I think using raw_response may be fine. I am OK with closing rather than merging this PR.

I feel there should be some kind of higher level abstraction layer over these kinds of queries, but to be honest I am not enough of a solr expert to determine what the optimal python level API may be here (and am finding the solr documentation a bit lacking).

**Comment by acdha** [comment]
Agreed – I think one of the problems is that Solr is a long-running project so there's been a lot of evolutionary growth, which is great for getting features in but it's hard to abstract things when the query format and response formats vary so much.

**Comment by tejas-kale** [comment]
I would like to use this feature in an upcoming work project. What is the future of this request? If there is further work to be done, perhaps I can contribute? Thanks...

**Comment by acdha** [comment]
@tejas-kale: does the raw response output work for you? This code needs to be resynced with the current master branch but it should just be a convenience

**Comment by tejas-kale** [comment]
@acdha Yes, raw response should be sufficient...

**Pull request closed without merging**
