### PR TITLE
Added support for realtime get

### PR DESCRIPTION
**Pull request by anti-social**
See: http://yonik.com/solr/realtime-get/

With this feature it is possible to use Solr as NoSQL database.

This pull-request https://github.com/toastdriven/pysolr/pull/74 doesn't support ids argument. Also Solr supports only id and ids parameters.

### CODE REVIEW

**Comment by joekiller** [comment]
This is a pretty old PR but would be nice to have @acdha.

**Comment by acdha** [comment]
@joekiller Let's dust it off then – have you had time to test this pull-request?

**Comment by joekiller** [comment]
I monkey patched the methods in and they appear to work fine.  Will try to
give the PR a spin.

**Comment by joekiller** [comment]
I checked out the branch and ran the tests. Four failed but they are not related to the PR.  Also I was running solr 4.10 which may have made a difference.  The failing tests were:

  * `test__mlt`
  * `test__scrape_response`
  * `test_extract`
  * `test_more_like_this`

I've used the methods and they work as expected.  I'd give this a :+1:

**Pull request closed without merging**
