### PR TITLE
implement Solr.system_info

### PR DESCRIPTION
**Pull request by skirsdeda**
This is quite handy for checking solr version and such.

### CODE REVIEW

**Comment by skirsdeda** [comment]
Also fixed SolrCoreAdmin. It was putting all params into request body for whatever reason and Solr treated all requests coming from SolrCoreAdmin as action=STATUS (default) requests. So everything other that SolrCoreAdmin.status didn't work at all (double checked this on Solr 4 and 5).

This also shows that tests/admin.py is useless since it only checks if solr returns good status code somewhere in response. But then SolrCoreAdmin should at lease use the same error checking code which currently is in Solr class. And I'm reluctant to do this refactoring until PRs #170 and #171 are merged.

**Comment by skirsdeda** [comment]
@acdha This one fixes SolrCoreAdmin and adds ```system_info``` to get info about Solr instance. Should be merged.

**Comment by RabidCicada** [comment]
Could we get some attention on system_info?  I need something like this for my solr6 upgrades on django_haystack to switch retrieval of suggestions @acdha

**Comment by acdha** [comment]
Looks like we should start by rebasing this branch against the current master & checking our test coverage

**Comment by RabidCicada** [comment]
I've worked around it by simply checking for type of suggestions object returned...but think an explicit solr check would be good.  It'll prevent future dead code hanging around with ???why do we check type here??? thoughts.  Instead the check will be explicit and dead/legacy code can be eliminated:).

**Pull request closed without merging**
