### PR TITLE
Ignore clusterstate.json. Fixes #224.

### LINKED ISSUE #224: pysolr.SolrError: ('Unknown collection: %s", collectionname)
i am trying to use the pysolr api and i am getting this strange error my solr instance is in cloud mode with zookeeper running and i can even see the collection name inside the solr admin browser 
can anyone help with that ?
solr version running is 5.5.3 with zookeeper 3.4.6 on ubuntu server 16.01 with anaconda 3 and python 3

### PR DESCRIPTION
**Pull request by rokclimb15**
Remove clusterstate.json and listener since the node exists but Solr no longer updates it. This resulted in the collections property being overwritten with an empty state. Tested on Solr 7.7.2. Below is log output during a connection/index/search routine. Without clusterstate being watched the `ZooKeeper` class correctly connects to `live_nodes`, polls `collections`, and polls the collection state to get shards.

```
Updated live nodes: ['172.31.80.126:8983_solr', '172.31.85.226:8983_solr', '172.31.84.9:8983_solr', '172.31.87.69:8983_solr']
Updated aliases: None
Updated collection: ['staging']
Updated collections: {'staging': {'pullReplicas': '0', 'replicationFactor': '2', 'router': {'name': 'compositeId'}, 'maxShardsPerNode': '1', 'autoAddReplicas': 'false', 'nrtReplicas': '2', 'tlogReplicas': '0', 'shards': {'shard1': {'range': '80000000-7fffffff', 'state': 'active', 'replicas': {'core_node3': {'core': 'staging_shard1_replica_n1', 'base_url': 'http://172.31.85.226:8983/solr', 'node_name': '172.31.85.226:8983_solr', 'state': 'recovery_failed', 'type': 'NRT', 'force_set_state': 'false'}, 'core_node4': {'core': 'staging_shard1_replica_n2', 'base_url': 'http://172.31.80.126:8983/solr', 'node_name': '172.31.80.126:8983_solr', 'state': 'active', 'type': 'NRT', 'force_set_state': 'false', 'leader': 'true'}}}}}}
```

I attempted to run the test suite, but it looks like the Solr package referenced is 404 in the test script. Additionally, Solr 4 is unsupported at this point I think.

### CODE REVIEW

**Comment by acdha** [comment]
Is there any upstream documentation about this being deprecated? We should probably have some sort of documentation / release notes link since I'm assuming there's at least some older version of Solr someone is running where this still works.

**Comment by rokclimb15** [comment]
I wasn't able to find any official documentation, likely because this is the internal API of Solr with ZooKeeper and is subject to change. The "official" way to do this would be to call the Solr HTTP API.

I think it would make sense to do this in the context of a BC release and update the test suite to run Solr >= 7 (supported). I started to do that, but ran into a few snags with config files.

**Review by acdha — DISMISSED** [review]

**Comment by cclauss** [comment]
Please rebase to run the tests.

**Comment by cclauss** [comment]
@rokclimb15 Please rebase or close.

**Comment by rokclimb15** [comment]
Closing in favor of https://github.com/django-haystack/pysolr/pull/426

**Pull request closed without merging**
